### ISSUE TITLE
Crashes on Device.

### ISSUE THREAD

**Issue by ErAbhishekChandani** [Yalantis/Persei#29]
This is crashing in device but running fine in simulator , i also checked in your Example project but its also crashing in Example app when using with device, I am using 10.0.2 (iPhone 6s) Xcode 8.0 .

Error: - fatal error: unexpectedly found nil while unwrapping an Optional value 
(Menu View is nil always)

**Comment by ErAbhishekChandani** [comment]
Can you please look into this i need to integrate this in my project. Thanks

**Comment by rnkyr** [comment]
Hey @ErAbhishekChandani! Just checked your problem.
This happens because in example project `ViewController` doesn't retain `menu` property. So all what you need to run it without crash is remove `weak` attribute: http://joxi.ru/GrqvR4XioowDmz
This is not the problem in a component, just in example project. Will fix it and update soon.

**Comment by ErAbhishekChandani** [comment]
thanks for help i will check and close issue.

**Comment by ErAbhishekChandani** [comment]
Thanks its working.
